### ISSUE TITLE
Empty list renders as blank instead of []

### ISSUE THREAD

**Issue by belvedere-trading** [ConfigHubPub/ConfigHubPlatform#10]
Hey there,

I've noticed that an empty list doesn't appear to render properly in files (blank instead of [] as I would expect). Can you confirm if this is an issue or I'm doing something incorrectly?

Thanks.

**Comment by edoarsla** [comment]
Assume file foo.json specifies a ${ key }.
If "key" *has no properties* defined that resolve context "Development;App", resolving "foo.json" with the same context will result in a blank string response for ${ key }.

However, if there is a value assigned to "key" that will resolve this context, even though this value is blank - the file resolution will return [""] for an array, or {"":""} for an object.

We distinguish between undefined and blank.

Does this make sense?

**Comment by belvedere-trading** [comment]
Yeah, that makes sense. To us, if we don't have any value for something that would represent an "error" in the way that we've configured things. So all good there.

Seems like the issue here is that there's a big difference between an empty list (`[]`) and a list with a single empty string within it (`[""]`). Usually what we'd like to do is configure empty lists as list key default, but I don't think it's possible to do that currently.

**Comment by edoarsla** [comment]
I see your point.  Let me see if we can get that into today's build.

**Comment by belvedere-trading** [comment]
Awesome, thanks!

**Comment by edoarsla** [comment]
Sorry, there might be some misunderstanding on my end.

What is the data-type of the key you are setting:  List or JSON?
And what exactly is the value you define?  Blank, "[]" or do you not define a value with resolvable context?

**Comment by belvedere-trading** [comment]
It's List. If you delete the blank value from the list, it says "null list" but then renders as blank in the file instead of as `[]`.

**Comment by edoarsla** [comment]
Now I get it - sorry, late starter this morning.  You're completely right, it should be [].
We'll make it so - same for map {}.

**Comment by edoarsla** [comment]
This is fixed as of v1.3.6.
https://github.com/ConfigHubPub/ConfigHubPlatform/releases/tag/v1.3.6
