### ISSUE TITLE
Tomcat support

### ISSUE THREAD

**Issue by ffurlanetto** [ConfigHubPub/ConfigHubPlatform#107]
Hello,

I have a client really interested to implement your product into their company, sadly they have a security requirement to run the application on a Tomcat server (TomEE is not allowed by their security policies)

Is their any plan to provide such version?

I already had a look at the project code and it is not using full J2EE stack features. Moving to J2EE Web profile should be quiet straightforward.

Anyway, I rise this issue to open the discussion. If you might be interested to support Tomcat, just let me know I'll be happy to assist you on this support.

Best Regards,

Florian

**Comment by edoarsla** [comment]
Is a docker container allowed?

**Comment by ffurlanetto** [comment]
Yes but they will audit the process running in it... I know by advance they will ask to rebuild the container on Tomcat base.

**Comment by grimwm** [comment]
I am working on a fix related to something else, but I am trying to get docker up with tomcat and the ROOT.war that the code generates.  I'll create a pull request soon if it works.
