### ISSUE TITLE
Team-level repository permissions don't take effect for files

### ISSUE THREAD

**Issue by belvedere-trading** [ConfigHubPub/ConfigHubPlatform#12]
Hey there,

We've been making use of team-level permissions for keys to great effect. I've just noticed that those same permissions don't apply for file modifications; I suspect that once we transition all of our devs to use the system, this could become a large issue (as it's very easy to accidentally modify the default context for a file without understanding what you're doing). Could we get those permissions to apply for file modifications as well?

Thanks,
Jordan

**Comment by edoarsla** [comment]
On the list - we'll bump it up and put it in the next release.

**Comment by edoarsla** [comment]
Resolved in v1.3.7.

https://github.com/ConfigHubPub/ConfigHubPlatform/releases/tag/v1.3.7
