### ISSUE TITLE
Minor UI bug when moving members between teams

### ISSUE THREAD

**Issue by belvedere-trading** [ConfigHubPub/ConfigHubPlatform#13]
Hey there,

In the "Teams" tab for a repository, we have the option to move users from one team to another by clicking an arrow next to their name and then clicking on the name of another team. This feature works properly on the backend; however, the UI switches the view to the team that you've moved the user into without changing the selected tab on the left or the team name label along the top. This is pretty confusing as I ended up thinking I'd accidentally moved myself into the wrong team!

Thanks,
Jordan

**Comment by edoarsla** [comment]
We'll address this in the next release.  Thanks for the heads up.

**Comment by edoarsla** [comment]
Fixed in v1.3.7.

https://github.com/ConfigHubPub/ConfigHubPlatform/releases/tag/v1.3.7
