### ISSUE TITLE
Ability to "copy" file from UI

### ISSUE THREAD

**Issue by belvedere-trading** [ConfigHubPub/ConfigHubPlatform#14]
Hey there,

Related to my previous request to apply team-level permissions at the file level, a nice feature would be the ability to open up an existing file (say at the default context level, something that's currently being using in production) and click a button that would "clone" the file into a different context level. This would allow individual users to quickly make changes to file that they are able to test locally before pushing up a change for approval and merge at the default context level.

Thanks,
Jordan

**Comment by edoarsla** [comment]
We agree, this is already on our list.

**Comment by edoarsla** [comment]
File clone functionality added in v1.5.
https://github.com/ConfigHubPub/ConfigHubPlatform/releases/tag/v1.5
