### ISSUE TITLE
ConfigHubFile VDT

### ISSUE THREAD

**Issue by belvedere-trading** [ConfigHubPub/ConfigHubPlatform#16]
Hey there,

We'd like to request a new VDT for keys. The purpose of this type would be to have values that refer to other file names within the same ConfigHub repository so that more complex "nested" configurations can be dynamically created based on run-time configuration resolution within individual applications.

Values for this type would only be valid if there is a file in the same repository with a name that exactly matches the value. A nice QOL feature would be to have the entry of this type include a dropdown of the current file names within the repository.

Thanks,
Jordan

**Comment by belvedere-trading** [comment]
Forgot something important - when files containing this value are rendered, I think they should come back in the same way that the `Text` VDT does today... Unless you're able to render the file as a nested object (which would be amazing, but seems like it could be difficult).

**Comment by edoarsla** [comment]
We agree.  More details in the near future.

**Comment by edoarsla** [comment]
This is implemented in v1.5.  Details are included in the release notes.
https://github.com/ConfigHubPub/ConfigHubPlatform/releases/tag/v1.5
