### ISSUE TITLE
File Creation/Modification via PUSH API documentation?

### ISSUE THREAD

**Issue by DennisHarper** [ConfigHubPub/ConfigHubPlatform#18]
Edin,
I see that you added the ability to push files via the API, however I do not see any documentation. Can you point me to any documentation that might exists for that?

Thanks,
Dennis

**Comment by edoarsla** [comment]
Hi Dennis,

I will.  In the meantime, in your upload JSON file you can add:
```
data: [
   {
      "content": "content of the file",
      "file": "foo/bar/test.txt",
      "context": "*;*"
    },
    {
      "content": "content of the file",
      "file": "foo/bar/test.txt",
      "context": "Production;*"
    }
]
```

**Comment by DennisHarper** [comment]
Great... Thanks!
