### ISSUE TITLE
Type awareness for files

### ISSUE THREAD

**Issue by belvedere-trading** [ConfigHubPub/ConfigHubPlatform#2]
Currently, we're able to define files using any format that we wish. This is a great property; however, it opens up the possibility of defining a file that doesn't match its expected format. It would be nice to be able to define the intended type of a file (within reason, something like `application/json`, `application/xml`, etc.) and have ConfigHub validate that the file definition is correct before allowing changes to be saved.

Specifically, for us, `application/json` validation would be enough.

**Comment by edoarsla** [comment]
This is supported as of v1.3.3
