### ISSUE TITLE
Regression in key name changes

### ISSUE THREAD

**Issue by belvedere-trading** [ConfigHubPub/ConfigHubPlatform#20]
Hey there,

I think we've run into a regression with key name changes. When I attempt to change the name of a key (on 1.4.0), I get the following error: Another file with the same context exists.

Let me know if you need more info.

Thanks,
Jordan

**Comment by edoarsla** [comment]
I do.  I tried reproducing with different combinations of a key usage, and all are ok.
As a sanity check, would you mind refreshing the page / of clear cache in the browser - just to make sure some JS is not from the old version (should not be, but just in case.)

Thanks,
Edin

**Comment by belvedere-trading** [comment]
Same issue after all of that. The key is included in two different files. Here's a screenshot: http://imgur.com/a/cii3S

**Comment by belvedere-trading** [comment]
By the way, I'm trying to change the name from `ServiceUser` to `BtPython.ServiceUser`

**Comment by edoarsla** [comment]
Just a thought.  Is this ConfigHub instance pointing to the same database, which you recently upgraded from version 1.3.3?  The version that had issues with file creation?  If so, could you check if you have files with same name and same context defined (that version allowed that).  If you remove context from the files page, you will be able to see them all.

**Comment by edoarsla** [comment]
The through here is - if indeed you do have more than one file with the same name/context, that use the key - this condition would be encountered.

When you rename the key - files that reference it also get updated.  If the file is updated, at the time of persisting them, a name/context check is made, and this condition would throw an error.

**Comment by belvedere-trading** [comment]
Ah, yes we probably do. I'll take a look at the database and let you know. Thanks.

**Comment by belvedere-trading** [comment]
That was it. I guess there should be a database constraint to prevent that situation. All good for now.

Thanks,
Jordan

**Comment by edoarsla** [comment]
Agreed.  We'll make it so.
