### ISSUE TITLE
Current docker image error.

### ISSUE THREAD

**Issue by ianido** [ConfigHubPub/ConfigHubPlatform#212]
Hi, the 1.8.1 docker image  (latest) failed starting: (here is the log)

^[[m^[[37m2023-08-01 08:29:41,475 INFO HHH000412: Hibernate Core {5.2.17.Final}                                                                                              
^[[m^[[37m2023-08-01 08:29:41,476 INFO HHH000206: hibernate.properties not found                                                                                             
^[[m^[[33m2023-08-01 08:29:41,482 WARN HHH000059: Defining hibernate.transaction.flush_before_completion=true ignored in HEM                                               
^[[m^[[37m2023-08-01 08:29:41,529 INFO HCANN000001: Hibernate Commons Annotations {5.0.1.Final}                                                                              
^[[m^[[37m2023-08-01 08:29:42,289 INFO HHH000400: Using dialect: org.hibernate.dialect.PostgreSQL95Dialect                                                                   
^[[m^[[37m2023-08-01 08:30:04,814 INFO HHH000424: Disabling contextual LOB creation as createClob() method threw error : java.lang.reflect.InvocationTargetException       
^[[m^[[37m2023-08-01 08:30:04,815 INFO HHH000270: Type registration [java.util.UUID] overrides previous : org.hibernate.type.UUIDBinaryType@5e7b2216                         
^[[m^[[37m2023-08-01 08:30:04,819 INFO Envers integration enabled? : true                                                                                                    
^[[m^[[33m2023-08-01 08:30:05,667 WARN HHH020003: Could not find a specific ehcache configuration for cache named [org.hibernate.cache.spi.UpdateTimestampsCache]; using defa
^[[m^[[37m2023-08-01 08:30:05,669 INFO HHH000250: Starting update timestamps cache at region: org.hibernate.cache.spi.UpdateTimestampsCache                                  
^[[m^[[33m2023-08-01 08:30:05,670 WARN HHH020003: Could not find a specific ehcache configuration for cache named [org.hibernate.cache.internal.StandardQueryCache]; using de
^[[m^[[37m2023-08-01 08:30:05,673 INFO HHH000248: Starting query cache at region: org.hibernate.cache.internal.StandardQueryCache                                          
^[[m^[[33m2023-08-01 08:30:05,770 WARN HHH020003: Could not find a specific ehcache configuration for cache named [com.confighub.core.system.SystemConfig]; using defaults.  
^[[m^[[37m2023-08-01 08:30:06,044 INFO HHH000397: Using ASTQueryTranslatorFactory                                                                                            
^[[m^[[37m2023-08-01 08:30:06,632 INFO HHH000204: Processing PersistenceUnitInfo [                                                                                         
        name: ConfigHubMain                                                                                                                                                  
        ...]                                                                                                                                       
^[[m^[[33m2023-08-01 08:30:06,634 WARN HHH000059: Defining hibernate.transaction.flush_before_completion=true ignored in HEM                                                 
^[[m^[[37m2023-08-01 08:30:06,645 INFO HHH000400: Using dialect: org.hibernate.dialect.PostgreSQL95Dialect                                                          
^[[m^[[37m2023-08-01 08:30:06,860 INFO HHH000424: Disabling contextual LOB creation as createClob() method threw error : java.lang.reflect.InvocationTargetException         
^[[m^[[37m2023-08-01 08:30:06,860 INFO HHH000270: Type registration [java.util.UUID] overrides previous : org.hibernate.type.UUIDBinaryType@5e7b2216                         
^[[m^[[37m2023-08-01 08:30:06,861 INFO Envers integration enabled? : true                                                                                                  
^[[m^[[37m2023-08-01 08:30:06,979 INFO HHH000250: Starting update timestamps cache at region: org.hibernate.cache.spi.UpdateTimestampsCache                                  
^[[m^[[37m2023-08-01 08:30:06,979 INFO HHH000248: Starting query cache at region: org.hibernate.cache.internal.StandardQueryCache                                            
^[[m^[[37m2023-08-01 08:30:07,083 INFO HHH000397: Using ASTQueryTranslatorFactory                                                                                          
^[[m^[[33m2023-08-01 08:30:07,252 WARN SQL Error: 0, SQLState: 42P01                                                                                                         
^[[m^[[31m2023-08-01 08:30:07,252 ERROR ERROR: relation "systemconfig" does not exist                                            
  Position: 239                                                                                                                                                            
^[[m^[[37m2023-08-01 08:30:07,259 INFO ConfigHub Version: 1.8.1                                                                                                     
^[[m^[[37m2023-08-01 08:30:07,270 INFO ConfigHub Shutdown

**Comment by wilstoff** [comment]
The latest public image on docker is out of date, we currently don't have permissions to update it.  Please compose it locally from source.

**Comment by ianido** [comment]
I build new image in dockerhub with v1.10.1 here: https://hub.docker.com/r/nearsolutions/confighub
It is important to mention that the database must be generated, it is not automatically generated when application load
