### ISSUE TITLE
I think the Export API is missing the content-type

### ISSUE THREAD

**Issue by DennisHarper** [ConfigHubPub/ConfigHubPlatform#25]
Edin,
The pull API has the content-type field for files, however the export API does not. Is this an oversight, or is this something that intentionally is not included?

Thanks,
Dennis

**Comment by edoarsla** [comment]
Hi Dennis.  We did not include it in export, as export was meant to be a counterpart to push - and in push, you do not specify a content-type.  We considered it a PULL (both forms) specific.

Are you using export beyond preparation for push?  If you could give us your use-case, we might start shifting our views.

Thanks,
Edin
