### ISSUE TITLE
See the files in which a property is referenced?

### ISSUE THREAD

**Issue by scottherlihy** [ConfigHubPub/ConfigHubPlatform#29]
Is there a way to see the list of files where a property is referenced?

Right now when I hover over a property is shows me the number of files that it is referenced in, but when I click on the number of files it doesn't show them to me. Is there somewhere else I should be going to view this information?

![image](https://user-images.githubusercontent.com/7905974/27989125-61db336e-63f7-11e7-9bbc-0b109e0166e6.png)

**Comment by edoarsla** [comment]
No, that is, not from the "Properties" page - we will make this change, as we agree it would be useful.
However, if you go to the "Files" page, and do a search for the key - in your case "SelfExtractingExeDropsiteLocation", the list of files specifying that string/key will return.

**Comment by scottherlihy** [comment]
Okay, great. That will be a good work around in the meantime. Thanks.
