### ISSUE TITLE
File creation API call

### ISSUE THREAD

**Issue by belvedere-trading** [ConfigHubPub/ConfigHubPlatform#3]
How difficult would it be to expose an API call to accept new file definitions programmatically? We're planning on storing a subset of our configuration data (could be thought of as the "schema" of our configurations in a way) in version control; we can then continuously sync the latest version of our VCS to ConfigHub.

We have this sync working well for individual configuration atoms, but it would be great if we were able to extend this solution to include our file definitions as well. Some API similar to the existing PUSH would be enough to accomplish our goals.

**Comment by edoarsla** [comment]
Should not be a problem.  We'll include it for the next build.

**Comment by edoarsla** [comment]
You may do this via PUSH API as of v1.3.3.
