### ISSUE TITLE
Save File Closes File Edit

### ISSUE THREAD

**Issue by scottherlihy** [ConfigHubPub/ConfigHubPlatform#31]
This may be by design, but when I save a file after editing it it closes automatically and returns me to the list of files page. This can be frustrating because the typical workflow I exhibit is updating the file/saving it and then attempting to update the values that will resolve. This is easily solved by me simply not saving until I update the values that resolve, but I would imagine this is a typical workflow and that perhaps not exiting on save is desired.

**Comment by edoarsla** [comment]
That was by design. We thought the normal use case is what you are doing now - make all changes, then save.
