### ISSUE TITLE
Referencing Context Values in File

### ISSUE THREAD

**Issue by scottherlihy** [ConfigHubPub/ConfigHubPlatform#33]
Is there a way to reference Context Values in a file?

For example if I had the context {Environment:Dev, Service:AGreatService} is there a way to reference the values Dev and AGreatService in the file the same way I reference properties, i.e. ${Environment} and ${Service}?

**Comment by edoarsla** [comment]
From files, you reference property keys. Values are resolved based on request context. 

With that said, a file may be assigned a context as well. 

Does that answer the question, or did I misunderstand it?

**Comment by scottherlihy** [comment]
What I want to be able to do is reference the values (that are resolved based on my request) from the files themselves. I understand that this may be a request specific to the implementation we are using so I will try to present an example.

If I had a UnitFile stored as a file in ConfigHub I would provide a context { Environment:Dev, Service:MyService} and all the property templates I have in the file would be resolved based upon the context. This is all relatively straightforward and works great right now. What I would like is to be able to also reference the context values I supplied in the file itself. I, of course, could do this myself when I get the file back from ConfigHub considering I already have the information (Dev, MyService) since I supplied it in the first place, but if I had a property that was something like PathToService I would like to be able to do something like this to render that extra work on my end unnecessary:

` "PathToService": "${BasePath}\AllServices\${Service}\site-packages"\etc`

(Where Service resolves to MyService)

**Comment by edoarsla** [comment]
I see. So you'd like to reference a context item name. 

No. There is no way you can do that right now. 

As a workaround, you could create a key with a value: MyService and context MyService, which would then resolve correctly. 

Second option, and I admit, it's an ugly one. In the JSON response, you get back the request context from which you could parse out the context. 

Lastly, if this is an important issue, we could discuss adding a different syntax for the context item resolution. Something like:  ${context:Service}, as an example.

**Comment by scottherlihy** [comment]
Okay. I think the first option is a fine work around for now. I have it working and this is by no means an important issue, but I would consider this a nice-to-have because I can envision other scenarios with this being useful going forward. Perhaps we could mark this as a feature request and if you guys have the time and bandwidth to take it on you can.

**Comment by edoarsla** [comment]
Sounds good. I'll mark it as enhancement.

**Comment by scottherlihy** [comment]
Great, thanks.
