### ISSUE TITLE
Ability to permission who can edit context values

### ISSUE THREAD

**Issue by belvedere-trading** [ConfigHubPub/ConfigHubPlatform#34]
Hey there,

I was wondering if there is any way to restrict who is able to change the values available within each context? Ideally I'd like to configure out instance so that only admins can add/delete/modify the available values within each context element.

Thanks,
Jordan

**Comment by edoarsla** [comment]
Hi Jordan. No, there's currently no way to do that.  Currently all users can manage context items, as long as they have editing permissions for prop values and files that use them.

**Comment by belvedere-trading** [comment]
Just want to make sure I'm being clear about what I mean here (reread what I wrote yesterday and I'm not sure if we're talking about the same thing). Right now we have two available environments: Dev and Prod. I'd like to be able to prevent individuals from adding some other random environment without first consulting with our ConfigHub admins. Adding actual values is not a problem as we already have the team permissioning working well.

--Jordan

**Comment by edoarsla** [comment]
Yes. We are talking about the same thing - I understood your question.  Certainly, this can be added, but right now there's no setting for this.

**Comment by belvedere-trading** [comment]
Gotcha. Cool, let's turn this into a feature request then if you guys agree that it could be a useful option. I was thinking it could either be encompassed into the team permissions or have its own toggle in the repository features section.

**Comment by edoarsla** [comment]
Implemented in v1.6.2.

For repositories owned by organizations, owners and/or administrators will find a new toggle in "Settings > Features" labeled "Context element managed by admins and owners only".

If switched on, only owners/admins can add/modify/delete context elements.
