### ISSUE TITLE
Permissions clarficiation

### ISSUE THREAD

**Issue by belvedere-trading** [ConfigHubPub/ConfigHubPlatform#35]
Hey there,

Looking for a little bit more clarification on how permissioning works through teams. Right now, I'm trying to set it up so that basically developers can edit only things that are fully specified AND within the dev environment. So a developer would not be able to edit `Dev;ServiceName;*` but would be able to edit `Dev;ServiceName;someinstance`. Really I don't think I am understanding what resolves/contains means when it comes to the team permissioning. Could you shed some light on whether this is possible? If not, could we get something like that added?

Thanks,
Jordan

**Comment by belvedere-trading** [comment]
Quick update - I was able to get this working with a combination of 3 rules. I have the fallthrough set to stop on first match and the default permission read/write. My 3 rules (all read-only) are:

1. Context resolves `Prod;*;*`
2. Context resolves `Dev;Default;*`
3. Context resolves `Dev;*;Default`

Default is just a sentinel that I added as an option for all of our contexts. So I do have this all working, but further clarification would be nice!

--Jordan

**Comment by edoarsla** [comment]
Hi Jordan,  sorry, this one slipped my radar.

"Resolve" in a rule means - values' context is treated as a request context against rules' context.  If its resolved, rule is applied.

"Contains" means each of the values' specified context items has to be contained within the rules' context items for the rule to apply.

Does this make sense?

**Comment by belvedere-trading** [comment]
Yup all good!
