### ISSUE TITLE
Is there a way to truncate the confighub_requests database?

### ISSUE THREAD

**Issue by lemongrabber** [ConfigHubPub/ConfigHubPlatform#37]
I think this is what's taking up a large amount of disk space on our server. Is there a safe way to delete old rows from this table?

**Comment by edoarsla** [comment]
Yes, you can safely remove any record from the API database, table ClientRequests.  

Just to add to that, we have a feature request to optionally not require this database, but rather log all requests to a log file.  There are obvious benefits to that, and then you can use log management tools to track requests.
