### ISSUE TITLE
Alphabetical sorting within sorting by context relevance 

### ISSUE THREAD

**Issue by scottherlihy** [ConfigHubPub/ConfigHubPlatform#38]
Below is an example of two different properties and the order they appear. They are both sorted by 'context relevance', but since within the given context (Dev) they were inserted at different times they appear in different orders. I would like it so that by default within a given context that it is sorted alphabetically.

![image](https://user-images.githubusercontent.com/7905974/28720848-ed2ab544-7373-11e7-84fa-be272026f409.png)

**Comment by edoarsla** [comment]
I hear you.  The only reluctance I have with that idea is that it may slow the render - if for example you don't specify context, and there are lots of values per key, etc.

**Comment by scottherlihy** [comment]
That's valid. Can it be provided along the same lines this exists today?

![image](https://user-images.githubusercontent.com/7905974/28724823-fc2676f2-7380-11e7-8f12-4b5108c02570.png)

**Comment by edoarsla** [comment]
Yes, that's a good point - that would be a good place for it.   I'll reopen it and make as enhancement.  Currently, there are some high priority items we're working on, so no promises on the time.

**Comment by scottherlihy** [comment]
No rush at all. Most of the things I have been posting are nice-to-haves moving forward as we begin to use ConfigHub more. Just want to work towards always improving the usability.
