### ISSUE TITLE
Ability to delete Configs via push api

### ISSUE THREAD

**Issue by DennisHarper** [ConfigHubPub/ConfigHubPlatform#39]
Is it possible to delete configs via the push api?

**Comment by edoarsla** [comment]
Interesting…. No, but I can see how that would be useful.  Are you thinking something like:
Key & context | action: delete

**Comment by DennisHarper** [comment]
Yeah, that would be perfect!

**Comment by belvedere-trading** [comment]
Just want to add, this is pretty important from a management perspective. We're working around it for now by modifying these values to empty strings to serve as a soft delete, but that leaves a bunch of bad-looking configs around.

**Comment by edoarsla** [comment]
Got it.  It will be in the next release.

**Comment by edoarsla** [comment]
Added to v1.6.1 - usage:  http://docs.confighub.com/en/latest/pages/schema/push.html
