### ISSUE TITLE
Locating orphaned configurations

### ISSUE THREAD

**Issue by belvedere-trading** [ConfigHubPub/ConfigHubPlatform#4]
Hey there,

Is there currently any way for us to locate keys that are orphans (i.e. no files refer to them)? This would be very useful from an operational standpoint to ensure that only relevant configurations remain stored in ConfigHub.

**Comment by edoarsla** [comment]
Hi.  Were you looking to do this programmatically - i.e. via API, or are you looking to do it through the UI?

**Comment by belvedere-trading** [comment]
Both would be ideal. For the short term UI would be fine, but I could foresee a good amount of usefulness being able to schedule these at some interval programatically.

**Comment by edoarsla** [comment]
In the UI, there is currently a way to do this.  You can:

1. Leave your context blank.
2. Click the "All" button.

All keys are returned, and those that have no values assigned will be visible (there are no values for them).  Mousing over them, will reveal if they are used in any files or not.

While recognizing this is only usable for very small datasets, we can come up with a generic way to get this data.

**Comment by edoarsla** [comment]
This is implemented as of v1.6.2.  In a repository > Settings > Cleanup
you will be presented with the list of keys (if any) that are orphaned.  You can delete them all in a single shot.
