### ISSUE TITLE
Delete all configs with no values associated with them

### ISSUE THREAD

**Issue by scottherlihy** [ConfigHubPub/ConfigHubPlatform#40]
Hello,

Would it be possible to add an enhancement that allows for repository wide deletion of both properties and ConfigKeys that have no values associated with them. Currently there are views at both the property level and the ConfigKey level that shows whether or not there are any values or properties associated with it respectively, but it would be nice to just have a button that finds and deletes all of these full stop.

Thanks, Scott

**Comment by edoarsla** [comment]
Yes, we’ll add it to the list of features to add.

**Comment by scottherlihy** [comment]
Thanks.

**Comment by edoarsla** [comment]
Implemented in v1.6.2.

Added to "Settings > Cleanup".  This will let you delete all keys that have no values and are not referenced by any files.

In the next release, we will also add context elements not used by any keys.
