### ISSUE TITLE
Key-level permissions not working

### ISSUE THREAD

**Issue by belvedere-trading** [ConfigHubPub/ConfigHubPlatform#41]
Hey there,

We've run into an issue with permissions once again. The "when key is" permission appears to not work at all. Our intent right now is to give a certain team full access to a small subset of keys regardless of their context, but we have not been able to get this to work at all. Same goes for "when key contains".

Thanks,
Jordan

**Comment by edoarsla** [comment]
I see it.  We're on it.

**Comment by belvedere-trading** [comment]
Awesome, thanks!

**Comment by edoarsla** [comment]
Fixed in v1.6.1
