### ISSUE TITLE
Service locked up on us today, hard restart required

### ISSUE THREAD

**Issue by belvedere-trading** [ConfigHubPub/ConfigHubPlatform#42]
We encountered a strange issue today where the ConfigHub service locked up completely requiring a hard restart. Our distributed daemons protected us from significant impact, but this could be a big problem for others running with direct connections to the service. 

The shutdown of the service took ~15-20 seconds while the subsequent startup took ~77 seconds (going from the logs). After the restart everything has been stable.

Please let me know what logs/diagnostics we can provide to help you guys look into this.

**Comment by edoarsla** [comment]
It would be awesome if we could have the time section of the server.out and configHub.log.  Could you let us know the version you're running.

What type of host are you running on - VM or metal?  Do you know if there were any host or network issues at the time - connectivity to the database (that would be visible in both confighub.log and server.out).

**Comment by edoarsla** [comment]
Another thing that would be interesting to see is the access log from that time - to see if there was something doing a DoS type activity - just a blind shot.

**Comment by edoarsla** [comment]
The logs you sent do not show any problems.  There are no exceptions, warnings or disconnects (database).  If there was a memory issue there would be a Java exception recoded in server.out log.

Based on all information provided, considering you have a relatively sustained load (about 10 client resolution requests per second), and considering a very verbose TomEE log at shutdown with many messages like:
   org.apache.catalina.loader.WebappClassLoader checkThreadLocalMapForLeaks
I suspect this might be a server issue, and we will look more into this.   There was a Google Gson library issue with Tomcat server regarding memory leaks, but it has been resolved a while back.

If something like this should happen again, could you please get a thread dump.  You can do that with:
   [sudo] kill -QUIT <pid>

As a comparison, we run a demo instance, also on the VM, and it only goes down for upgrades.  Its too has a sustained load, but we never ran into an issue like this.

As we don't have anything else to offer to this thread at this time, I'll close the issue, but will reopen if there are new discoveries.
