### ISSUE TITLE
Allow owners/admins to remove security groups.

### ISSUE THREAD

**Issue by ummaycoc** [ConfigHubPub/ConfigHubPlatform#44]
If an owner/admin/etc loses a password for a security group, the security group can no longer be deleted.

**Comment by edoarsla** [comment]
We'll allow owners/admins to change security group passwords in the next release.

**Comment by edoarsla** [comment]
This is implemented in v1.6.4 - now available.  To make it a bit tighter, we are only allowing repository/organization owners (not admins), to recover the password.
