### ISSUE TITLE
Cannot input double value >= 100

### ISSUE THREAD

**Issue by thansen24** [ConfigHubPub/ConfigHubPlatform#45]
I created a new property of type double and tried to set it to 100 and the "Save property" button is disabled.  99 works just fine, but anything over 100 doesn't work.

![image](https://user-images.githubusercontent.com/32498632/31150228-7180daf8-a858-11e7-8a83-110cdfbcbcef.png)

![image](https://user-images.githubusercontent.com/32498632/31150296-ab5b0ad2-a858-11e7-8275-8b8f57557cd1.png)

![image](https://user-images.githubusercontent.com/32498632/31150262-8b8e23e2-a858-11e7-81bf-3155663368c0.png)

**Comment by edoarsla** [comment]
Cute :). Thanks for the heads up. We’re on it.

**Comment by belvedere-trading** [comment]
Minor piece of extra info, we verified that this was a UI bug by successfully setting the value via the push API.

**Comment by edoarsla** [comment]
Yes, we verified the same yesterday.  Given this new information, do you want us to cut a new build with the fix ASAP, or is it ok to roll the fix for the next release - within next 2 weeks?

**Comment by thansen24** [comment]
Waiting a few weeks is fine with me

**Comment by edoarsla** [comment]
Sounds good.  Thank you.

**Comment by edoarsla** [comment]
Fixed in v1.6.5
