### ISSUE TITLE
Doubles that are >0 and <1 should always be stored with a leading zero

### ISSUE THREAD

**Issue by thansen24** [ConfigHubPub/ConfigHubPlatform#47]
The UI allows me to store this for a double:

![image](https://user-images.githubusercontent.com/32498632/31189637-73f70522-a8fe-11e7-9e16-6a624a7ace74.png)

Which if you use this property in a JSON file will result in invalid JSON.

You need to explicitly go back and change it to this:

![image](https://user-images.githubusercontent.com/32498632/31189729-b0b2d22a-a8fe-11e7-8636-e4610f91f1db.png)

I would think the UI should always store a leading 0 if it's between 0 and 1 regardless of how the user enters the fractional number.

**Comment by edoarsla** [comment]
We'll fix this as part of the existing double/float UI fix.

**Comment by edoarsla** [comment]
Fixed in v1.6.5
