### ISSUE TITLE
Cannot create or edit context elements

### ISSUE THREAD

**Issue by belvedere-trading** [ConfigHubPub/ConfigHubPlatform#48]
With the most recent release, we're not able to create or edit context elements. The message we get is "Only owners and administrators of this repository are allowed to manage context elements."; however, even owners and admins cannot make changes. Furthermore, the Features tab does not allow this feature to be enabled or disabled (it shows as disabled always despite locking the contexts).

I'd consider this a high priority since we current are unable to edit context elements at all.

--Jordan

**Comment by edoarsla** [comment]
looking now

**Comment by edoarsla** [comment]
Testing v1.6.5 for both admin and team member, on repositories that are both private and organization owned - I did not run into any problems.

Would you please check that a database table “Repository” has a column “adminContextControlled”, and that values in that column are either 1 or 0.

**Comment by edoarsla** [comment]
Also, just to eliminate a potential of JavaScript caching issues - could you clear the cache, or try a different browser.  If this is the cause, we have a way of addressing this.

**Comment by belvedere-trading** [comment]
Definitely browser-side caching. Opening the site in an incognito windows resolved this. Sorry about the false alarm. Is there a way to force refreshes or something like that?

**Comment by edoarsla** [comment]
We add a version to each JavaScript file in the index.html page.  This forces the refresh on each update.  We do this as not all browsers handle expiration dates the same, and with Safari there’s always some issue.  This way we force the update, but you can still cache it between releases.

For example:  <script src="/js/app.js?v=11"></script>

However, it looks like we did not bump it in this release.

I’ll re-update this release with bumped versions - if/when you re-download to update other instances it will not have this issue.
I’ll do this in about 20 minutes.

Thanks,
Edin

**Comment by belvedere-trading** [comment]
Perfect. Thank you!

**Comment by edoarsla** [comment]
Re-published with updated version numbers for JavaScript files.
