### ISSUE TITLE
Default blank text value leads to NullPointerException during file resolution

### ISSUE THREAD

**Issue by belvedere-trading** [ConfigHubPub/ConfigHubPlatform#5]
Steps to reproduce:

1. Create a new key using the Text type.
2. Don't enter anything in the value.
3. Add the key to a file.

At this point, you won't be able to preview or issue pull requests for the file (500 internal server error).

If you update the blank value at any time (even if you leave it blank), this issue resolves itself and the file is correctly resolved with the empty string.

Seems like a minor edge case in new key creation.

**Comment by edoarsla** [comment]
Good catch.   Fixed.  We're publishing a new release in the next hour or so.  I'll let you know when its available.  This will also include other features we communicated about - File APIs, Mime-Type headers, as well as broader (file supporting) export/push APIs.

**Comment by edoarsla** [comment]
FYI, this is fixed in v1.3.3 - just released.
