### ISSUE TITLE
Question: Does confighub handle it's own database upgrades and schema migrations?

### ISSUE THREAD

**Issue by samrocketman** [ConfigHubPub/ConfigHubPlatform#55]
# Question

Does confighub handle it's own database upgrades and schema migrations?

I'm looking through the documentation and haven't found any docs relating to DB upgrades, yet.

Will the application handle this itself?  If you haven't planed for this, yet, have you looked at how to handle it in general?  I'm currently looking at liquibase in case I get handed an sql file for DB migrations.

**Comment by edoarsla** [comment]
Yea.  This is all still a bit primitive.  Major upgrades come with upgrade SQL script.  For example, in the last release its in the  `upgrade/upgrade-v1.7.sql` file.  And no, it does not do it by it self - you have to run the upgrade script.

**Comment by samrocketman** [comment]
Thanks for letting me know.  I'll try to bake my own database migration client in Java.  When I do, I could probably share it back to you with an open license or unlicense so you can see how I'm doing it.  The desire being that it is preferable for an application to manage database upgrades, migrations, and rollbacks.

**Comment by samrocketman** [comment]
Would it be possible for you guys to create a GitHub repository with database/schemas posted for major versions?  This way I can reference it as a source and have a place to contribute back.

**Comment by edoarsla** [comment]
Yes.  I'll try to move all code to open-source repo over the next week.  Your contributions are more than welcome.  We do need a better strategy for managing database upgrades.

**Comment by samrocketman** [comment]
Well, hopefully I can come up with a good way for you to migrate the DB.  Is the confighub application itself Java?

**Comment by edoarsla** [comment]
Yes, its a JavaEE application running on a Tomee server.  We use JPA -> Hibernate (with Envers).

Currently, we're not doing the correct thing, in that, new schema is generated on startup, and for schema modifications we provide SQL instructions.

We want all schema modifications to be external to the application, and only want the application to do schema validation at startup.   Currently, MySQL, MariaDB and PostgreSQL are tested and drivers come included in the distribution.

**Comment by sgleske-ias** [comment]
Do you guys only change database schema on major release?  (e.g. 1.6.X -> 1.7.X)

**Comment by earslanagic** [comment]
that's correct.

**Comment by sgleske-ias** [comment]
@edoarsla if you don't mind.  You could create a repository for me and I could populate it initially with database schema upgrades by downloading all of the versions you publicly provide.

I wouldn't mind doing that for you.  You can revoke my write access after it's created (or protect the master branch, whatever you decide).

**Comment by sgleske-ias** [comment]
Thinking of a layout along the lines of:
```
README.md
upgrade/1.6/upgrade-v1.6.sql
upgrade/1.7/upgrade-v1.7.sql
... etc
```

**Comment by earslanagic** [comment]
sure.  what would you like the repo name to be, and which (if not both) user accounts do you want to use?

**Comment by sgleske-ias** [comment]
You can add both accounts to it.  I use @samrocketman for after-hours work and @sgleske-ias for on-hours work.

I'm thinking name it `confighub-database-migrator`.  As I create a programmatic utility utility that will probably be its artifact name.

**Comment by sgleske-ias** [comment]
The utility will be dual-purpose as a jar which can be included in your application if you ever decide to host database migrations internally.  Or as a standalone executable for performing migrations as a separate action.

**Comment by edoarsla** [comment]
Ok, you're in https://github.com/ConfigHubPub/database-migrator with write privileges on both accounts :) . Thank you.  I'm really excited about making database management easier.

**Comment by sgleske-ias** [comment]
Does ConfigHub store the version of the currently running JVM instance in the DB?  To automatically relate the DB schema with the proper runtime version of ConfigHub.  It would also assist in automating the DB upgrades if we know the current version the existing schema is based.

**Comment by earslanagic** [comment]
It does not currently track version.  I have a non-committed version where it does, but I'll hold off on committing those changes.

**Comment by sgleske-ias** [comment]
No worries.  I'm thinking along the lines of:

```bash
#initialize migration support by setting the current version without changing any schema
java -jar database-migrator.jar --set-db-version 1.6
```

Where a user can see a list of versions they can set with:
```bash
#show what versions of ConfigHub which are supported for automatic database migration
java -jar database-migrator.jar --list-support
```

**Comment by earslanagic** [comment]
I love it!

**Comment by sgleske-ias** [comment]
Also, thinking of the migration looking along the lines of:

```
#migrate 1.6 to 1.7
java -jar database-migrator.jar --target-schema 1.7
```

The nice thing about liquibase is it can upgrade and downgrade.  So if someone decides they upgrade to 1.7 and want to go back to 1.6, then they can go back:

```
#roll back 1.7 to 1.6
java -jar database-migrator.jar --target-schema 1.6
```

I would depend on liquibase to handle all of the heavy lifting.

**Comment by sgleske-ias** [comment]
Okay, I'll close this issue later after work.  I'll start creating issues for work in the new repository you created.

Thanks @earslanagic

**Comment by earslanagic** [comment]
No, thank you @sgleske-ias

**Comment by sgleske-ias** [comment]
I downloaded 1.6 and 1.7.  I notice only 1.7 has a schema update.

Do 1.5 and 1.6 share the same schema and 1.7 the first release which has a schema migration?

**Comment by earslanagic** [comment]
They do.  Furthermore, if there are no objections, I can remove all download options for versions below v1.6.  There should be no reason to go below that version.  

The versioning strategy of major version signifying a schema change was established at only at v1.6.

**Comment by sgleske-ias** [comment]
Oh okay, I'll commit the 1.7 schema.  Can you create the 1.6 schema since I can't seem to be able to locate it?

**Comment by samrocketman** [comment]
@earslanagic please see my last question.

**Comment by edoarsla** [comment]
@sgleske-ias sorry for the delays, I will commit 1.6 schema over the weekend.

**Comment by edoarsla** [comment]
@sgleske-ias - I've added database-migrator:schema/v1.6.sql 
Please let me know if you need anything else from me.  I'll be faster to respond this time around :)

**Comment by samrocketman** [comment]
No worries, this hasn't blocked any work from me since my team is starting from ConfigHub 1.7.  I just figured we could start managing migrations from ConfigHub 1.6.
