### ISSUE TITLE
Docker tags do not match git tags in this repository

### ISSUE THREAD

**Issue by sgleske-ias** [ConfigHubPub/ConfigHubPlatform#56]
I'm also @samrocketman from #55.

Compare:
* https://hub.docker.com/r/confighub/confighubplatform/tags/
* https://github.com/ConfigHubPub/ConfigHubPlatform/releases

i.e. 1.7 has not been tagged in DockerHub.

**Comment by earslanagic** [comment]
Thanks for pointing that out.  We'll add it.  Right now latest in Docker is pointing to v1.7

**Comment by edoarsla** [comment]
Starting with v1.8 - they will all match
