### ISSUE TITLE
Added binaries?

### ISSUE THREAD

**Issue by samrocketman** [ConfigHubPub/ConfigHubPlatform#59]
It is a git anti-pattern to add binaries to the repository.  Your most recent change adds binaries which will cause the repository to grow greatly over time.

Recommendation:

- Modify git history removing all of the binaries.
- Add a gitignore entry to avoid accidentally adding the binaries by mistake.

**Comment by samrocketman** [comment]
@edoarsla I'm referring to commit https://github.com/ConfigHubPub/ConfigHubPlatform/commit/4fc4606620568ea4224c9303c290a855513181f8

On a side note: kudos to you for sharing the source (even if under proprietary license).  Having access to source code greatly increases my ability to troubleshoot software and does not force me to do silly things like decompile in order to investigate.  Thanks for sharing <3.

**Comment by edoarsla** [comment]
Still in the process of cleaning it up - thank you for the heads up.  Please do let me know if you notice anything odd.  I just removed the binaries, and will be switching the license to MIT.

**Comment by samrocketman** [comment]
@edoarsla can you squash (or fixup) this commit so the binaries aren't in the git history at all?  You'll have to force push the master branch but I think it's worth it to remove the binaries.

> Pro tip: before squashing be sure to save the git hash of your current checked out branch.  This way you can fall back to the old history if you feel you make a mistake.  Restore branch by `git reset --hard <saved commit hash>`.  Alternatively, `git reflog` is a history of your checkouts.

Example editing history to remove binaries:

```
git checkout master
git rebase --interactive ec032fb1512e8375fe0fc5826388a5bf1b3e36ac
# where ec032fb is one commit before the affected change
# follow the following instructions
```

1. This will bring up the interactive rebase editor for modifying commit history.  The oldest commit is at the top of the list while the newest commit is at the bottom.
2. You must have at least one commit with the word `pick` (kind of like `cherry-pick`).  In this case you want the oldest commit to be p`pick`.
3. On all newer commits change the word from `pick` to `fixup`.  This will combine the diff of all commits and discard the commit message of the commits designated for fixup.  Commits will be combined from bottom to top.
4. Save and exit the editor and the commits will be edited.  Use `git log` and `git diff --name-status HEAD~1` (shows just file list) to verify the binaries are removed.
5. Force push to master to overwrite history on GitHub.

Hopefully, if I'm too verbose or you have questions, then let me know.

**Comment by samrocketman** [comment]
The above removes the binaries from history which avoid users cloning binaries in history (even though you removed them from later commits).

**Comment by samrocketman** [comment]
I forked the repository so you have an extra backup as a precaution.

**Comment by samrocketman** [comment]
Accepted the invite.  Would you like me to fix the history?

**Comment by edoarsla** [comment]
I really appreciate your help with this project, and if you're willing, that would be quite welcome :)

**Comment by samrocketman** [comment]
Sure, I'll do it within the hour.  Please be sure the master branch is unprotected in project settings because a force push involves deleting/overwriting master.

**Comment by edoarsla** [comment]
All set.  I'm in Central time, and might not be up much longer.  I'll continue the license cleanup tomorrow.  Thank you!

**Comment by samrocketman** [comment]
I removed the `server` directory and added a `.gitignore` file.  Note: there's still a backup copy in my fork.  If there's files you need to preserve from the server directory you can get them from my fork (or I'm sure you have a local copy).

To update your local git repository master branch you can:

```
git checkout master
git fetch origin
git rebase origin/master
#your master branch is now up to date with origin master branch
```

That's all for now :+1:
