### ISSUE TITLE
Make repos "public"

### ISSUE THREAD

**Issue by scottherlihy** [ConfigHubPub/ConfigHubPlatform#64]
I am an admin of our ConfigHub instance that has its user base growing consistently and a pain point that I've found is that anytime a new user is created we need to manually add them to the correct permission group (Team) for EACH repo. 

It would be nice if there was a way to mark _some_ repos as "public" and then mark one of the teams (likely one without a lot of access to change things) in that repo default. How I would like this to then behave is that if a new user created account that they would automatically be assigned the permissions of the default team for all _public_ repos. Then if I wanted to give them different permissions I would just add them to another permission group in that repo and it would serve as an override.

**Comment by earslanagic** [comment]
So, there's something like this already.  If you go to a repository settings, and click on "Visibility", you can make a repository "Public".  This means, any newly registered user will be able to read-only the content of the repository, but will not be able to change anything.

Would this satisfy the problem, or do you think we should go further and apply the "default team" permissions?

**Comment by scottherlihy** [comment]
Thanks, that is good to know! For us at least I still think it would be useful to have the default team.

To illustrate why our main repos are set up with the context:

Environment > Service > Instance.

Our permissions for the most basic team in these repos are that anyone can edit "fully qualified contexts" (aka no stars) i.e. Dev>MyService>MyInstance provided that Environment != Prod. The default team in the Public repos would allow us to then say that anyone can have this ability to write to these without me explicitly adding them to a team

**Comment by edoarsla** [comment]
In v1.8, we're added LDAP support.  We are planing on using LDAP security group user assignment to map to the ConfigHub team - and therefore team permissions.  Would this address your problem?
