### ISSUE TITLE
Add Context Scope Items via API

### ISSUE THREAD

**Issue by ollieatseats** [ConfigHubPub/ConfigHubPlatform#65]
Is it possible to add new items to the context scope via the API, I looked but could not see anything documented?

![image](https://user-images.githubusercontent.com/20419909/38503322-a6d97aa8-3c09-11e8-9848-33741802bea1.png)

**Comment by earslanagic** [comment]
Yes.  For example:

```
/usr/bin/curl -k -i https://localhost/rest/push/<account>/<repository> \
   -H "Content-Type: application/json" \
   -H "Client-Version: v1.0" \
   -H "Application-Name: Push Test" \
   -X POST -d '{"enableKeyCreation": true, data: [ { "key": "A-Key", "values": [ { "context": "New_Context;*;*", "value": "123" } ] } ] }
                '
```

Will create a new context element "New_Context" - provided a key enables push-updates.

**Comment by edoarsla** [comment]
Should this issue be closed?
