### ISSUE TITLE
Confighub logs to local time

### ISSUE THREAD

**Issue by lemongrabber** [ConfigHubPub/ConfigHubPlatform#74]
We are trying to do some performance analysis of Confighub by analyzing the logs and correlating them to other things going on in our system at that time, but the confighub logs are in GMT, I we would like them to log using the locally configured timezone. Is there a simple config somewhere we can set to get this going or will it require more involved intervention?

Cheers,
Alex Shaffer

**Comment by edoarsla** [comment]
Yes, in .../server/bin/setenv.sh there's a line:
export JAVA_OPTS="$JAVA_OPTS -Duser.timezone=UTC"

If you comment this out, the server will user system timezone.

**Comment by lemongrabber** [comment]
Awesome!

Thanks for the quick reply Edin!

Alex
