### ISSUE TITLE
Spaces in ContextElements

### ISSUE THREAD

**Issue by scottherlihy** [ConfigHubPub/ConfigHubPlatform#77]
Would it be possible to add support for adding spaces to context elements?

Currently we receive the following error if spaces are attempted to be added

"Names may only contain alphanumeric characters or single hyphens, and cannot begin or end with a hyphen."

Example:
-"Something Index - S&P"

In general, I'd agree spaces should probably not be included in keys, but we have a bunch of legacy systems that have them and we'd need to sanitize everywhere we call them given the current requirements in CH.

**Comment by scottherlihy** [comment]
I guess while we're at it we also are requesting '&' support as well.

**Comment by scottherlihy** [comment]
Can we have an update on this in terms of if this is something that you would be able to support in the future or not?

**Comment by edoarsla** [comment]
Currently we do not have a plan to this feature.
