### ISSUE TITLE
Cant set empy list for list type in UI

### ISSUE THREAD

**Issue by scottherlihy** [ConfigHubPub/ConfigHubPlatform#78]
I cant seem to set list values as an empty list through the UI anymore. If I attempt to set it as an empty list and renders as null. If I attempt to set it to a list with a blank value it is set to an empty list with an empty string in it (aka [""]).

**Comment by earslanagic** [comment]
Will take a look. We're getting ready for v1.8 and will make sure this is addressed in there.

**Comment by scottherlihy** [comment]
Great, setting an empty list IS possible through the Push Api so there is a workaround for now

**Comment by scottherlihy** [comment]
FYI: Apparently the same is true for the map type

**Comment by scottherlihy** [comment]
@edoarsla was this indeed intended to be fixed in v1.8? We are running 1.8.3 and it appears to still be an issue.

**Comment by krystofurr** [comment]
In version v1.97 I cannot create a Map or List type configuration via the push API
