### ISSUE TITLE
Push API Enhancement

### ISSUE THREAD

**Issue by DennisHarper** [ConfigHubPub/ConfigHubPlatform#8]
Hello,
It seems that the Push API creates new keys if they do not exist already, however, it does not seem to create new Context property if it does not exist. For example, if a service is not already created, given a context signature of:
Environment, Service, Instance

A push to the API does not create a new Service, it just returns status_code of 303.

It would be great if the API did create these properties if they do not exist.

Thanks,
Dennis

**Comment by edoarsla** [comment]
As part of the response, you should also receive an "ETag" that would indicate the reason for the rejection.  Could you tell me what it says.

Currently, I am not able to reproduce this issue.

**Comment by DennisHarper** [comment]
The etag is:
{'data': [{'push': None, 'values': [{'active': True, 'value': 'windows_iis', 'context': 'Dev;DatabaseResolutionMethods;*'}], 'vdt': None, 'key': 'AutomationType', 'readme': None, 'deprecated': None, 'password': '', 'securityGroup': ''}], 'changeComment': u'TestAgain', 'enableKeyCreation': True}

Steps to reproduce:
1.	Create a new repo with the name MyTestRepo with the user myTestUser
2.	Create a new key with the Name 'MyKey' and type of Text
3.	Change the variable server to reflect your server name, an run the following python code.

`
import requests

server = "myserver"
username = "myTestUser"
repoName= "myTestRepo"

headers = {'Content-Type': 'application/json',  'Application-Name': 'TestApp'}
postData = "{'data': [{'push': None, 'values': [{'active': True, 'value': MyValue', 'context': 'Dev;MyService;*'}], 'vdt': None, 'key': 'MyKey', 'readme': None, 'deprecated': None, 'password': '', 'securityGroup': ''}], 'changeComment': u'TestAgain', 'enableKeyCreation': True}"

response = requests.post('http://{}/rest/push/{} /{}'.format(server, username, repoName), headers=headers, json=postData)
`

**Comment by edoarsla** [comment]
Looks like there are some errors in your data.  For example:

1. 'push': None   -> this should be a boolean value (true/false), or none at all.
2.  'changeComment': u'TestAgain'  -> you have "u'T"  this beaks the quotations
3. 'active': True, 'value': MyValue'  ->  quotations

Could you fix these errors and give it another go.

**Comment by DennisHarper** [comment]
The problem was I was adding None to values that should have just been omitted. Sorry for wasting your time and thanks for the help.

**Comment by edoarsla** [comment]
No worries.  Glad all is well.
