### ISSUE TITLE
Dockerfile for v1.8 fails on start up

### ISSUE THREAD

**Issue by ollieatseats** [ConfigHubPub/ConfigHubPlatform#81]
I have run the database upgrade and deployed v1.8 container but on startup I am getting the following error:

Writing database credentials to /confighub/server/conf/tomee.xml,
/init.sh: line 9: /confighub/server/conf/tomee.xml: No such file or directory,
Writing server configuration to confighub/confighub.sh,
2018-11-08 15:07:43,264 CRIT Server 'unix_http_server' running without any HTTP authentication checking,

I am passing the ENV: DB_DRIVER, DB_URL, DB_USERNAME, DB_PASSWORD that were used in v1.7.

Any help greatly appreciated.

**Comment by edoarsla** [comment]
Could you try updating the v1.8 image and trying again.  I just rebuilt and believe the problem is resolved.

**Comment by ollieatseats** [comment]
Hi

I redeployed the image and that worked.

Thank you so much for your efforts its very much appreciated.
