### ISSUE TITLE
Is there a flag to force a push?

### ISSUE THREAD

**Issue by DennisHarper** [ConfigHubPub/ConfigHubPlatform#9]
when push updates are disabled for specified key, is it possible to force a push?

Jordan mentioned that there was, but I was not able to find it in the docs.

Thanks

**Comment by edoarsla** [comment]
Hi Dennis.  No, there is no way currently to force a push for a push-disabled key.  Jordan had raised this question, and then sought feedback from your team.  I don't think there were any replies, and it stayed as is.

Here's the email thread:

```
On Mar 24, 2017, at 2:12 PM, Jordan wrote:

Adding Alex and Scott for some input on their end.

—Jordan

On Mar 24, 2017, at 2:05 PM, Edin wrote:

Bottom line, this is not a problem.  Its however worth a discussion about the strategy.

I think the right way to do this, would be for the PUSH to use a token, pre-authorized for key push 
overrides.  Is there anything that makes it difficult for you to use a token, and do you agree with this.

Thanks
Edin


On Mar 24, 2017, at 1:51 PM, Jordan wrote:

One quick question/request: with the push API, we currently have the ability to mark a key as
“disabled” for pushing. This is useful because it will allow us to essentially specify which keys should 
be dynamically updatable via our clients and which should not. I’m running into a bit of a Catch-22 with 
an operation aspect though - we want to be able to keep our configs in Git and push changes to 
ConfigHub. Right now, since this is using the same push Api as our clients, some keys would 
presumably not be able to be updated by this Git conversion process. Do you think there is a way 
(either through a separate endpoint, or perhaps a special override within the same push endpoint) for 
us to state that all pushes should be honored regardless of the setting on the key level? Let me know 
what you think

Thanks,
Jordan
```

**Comment by DennisHarper** [comment]
Thanks Edin,
After the discussion we just had, I think that the feature would be needed. The pre-authorization token would definitely be the way to go.

Let me know if I can do anything to help facilitate this request.

Thanks and have a good weekend,
Dennis

**Comment by edoarsla** [comment]
Sounds good.  We all agree token is the way to go.  We'll try to get this in for the next release this coming week.

**Comment by edoarsla** [comment]
Feature added in v1.3.6.
https://github.com/ConfigHubPub/ConfigHubPlatform/releases/tag/v1.3.6
