### ISSUE TITLE
Issue With Revision History On "Link To" Page

### ISSUE THREAD

**Issue by scottherlihy** [ConfigHubPub/ConfigHubPlatform#96]
We had an issue in yesterday that was rendered more difficult to solve because the revision history for a specific property (accessed by hitting "Options" > "Link To") did not show all changes to that property that had occurred that day. We were able to keep going through the revision history for previous days, but it appeared that the day in question was truncated.

When accessing the "Revisions" tab in the main drop down it did display all of the changes that had been made to that property. (For what it's worth, the change that was not displaying was an overriding of a * > * > * value to something more specific)

This inconsistent behavior might indicate that there is a limit on the number of results displayed per day on the "Link To" page, but not on the "Revisions" tab.

**Comment by edoarsla** [comment]
Yes.  The link-to page does have a limited set of changes returned.  When I implemented it, I thought of it as a poor-man implementation as a limited reference, and did not include pagination - therefore the limit to the number of past changes.

But you do make a good point, and this should follow the same pattern as the revision tab.
